# ===============================================================================================================#
# Copyright 2022 Infosys Ltd.                                                                                    #
# Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at  #
# http://www.apache.org/licenses/                                                                                #
# ===============================================================================================================#

[DEFAULT]
ENVIRONMENT = dev
APP_DIR_ROOT_PATH = /home/projadmin/workarea/docwbsln
APP_DIR_DATA_PATH=/nfs/docwbdx/data
APP_DIR_LOG_PATH=/nfs/docwbdx/logs

# Path to log file
log_file_path = %(APP_DIR_LOG_PATH)s
log_file_prefix = infy_dx_downloader_
log_to_console = true
logging_level = 10
# Possible Values for logging_level
; CRITICAL = 50
; ERROR = 40
; WARNING = 30
; INFO = 20
; DEBUG = 10


service_name = infy_dx_downloader
# make sure the version is same as the one kept in setup.py
service_version = 0.0.2
output_file_suffix = downloader_response



[WORKFLOW]
current_scheduler_stage_folder=app_scheduler_stage/downloader_completed

[APP_ARGS]
# use / for file paths
; master_config = %(APP_DIR_DATA_PATH)s/config/master_client_config.json
master_config = /nfs/docwbdx/config/master_client_config.json
