# =============================================================================================================== #
# Copyright 2020 Infosys Ltd.                                                                                    #
# Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at    #
# http://www.apache.org/licenses/ 
# ================================================================================================================ #



#URL
#docwb.base.url=http://localhost:8080/docwbservice
#docwb.username=john123
#docwb.password=john@123
#docwb.authenticate=true
docwb.base.url=http://localhost:8080/docwbservice
docwb.api.auth.url=${docwb.base.url}/api/v1/auth
docwb.api.doc.url=${docwb.base.url}/api/v1/document
docwb.api.doc.user.url=${docwb.base.url}/api/v1/document/user
docwb.api.action.url=${docwb.base.url}/api/v1/action
docwb.api.doc.attr.url=${docwb.base.url}/api/v1/attribute/document
docwb.api.attach.attr.url=${docwb.base.url}/api/v1/attribute/attachment
docwb.api.action.param.attr.recommendation.url=${docwb.base.url}/api/v1/action/param/attr/recommendation
docwb.api.template.flattened.url=${docwb.base.url}/api/v1/template/flattened
docwb.api.doc.attachment.url=${docwb.base.url}/api/v1/attachment/doc
docwb.api.doc.attachment.group.url=${docwb.base.url}/api/v1/attachment/doc/group
docwb.api.doc.attachment.file.url=${docwb.base.url}/api/v1/attachment/doc/file
docwb.api.attachment.email.file.url=${docwb.base.url}/api/v1/attachment/email/file
docwb.api.task.status.url=${docwb.base.url}/api/v1/document/taskstatus
docwb.api.event.type.url=${docwb.base.url}/api/v1/document/eventType
docwb.api.send.email.url=${docwb.base.url}/api/v1/email
docwb.api.attr.add.url=${docwb.base.url}/api/v1/attribute/add
docwb.api.email.url=${docwb.base.url}/api/v1/email/taskstatus
docwb.api.email.status.url=${docwb.base.url}/api/v1/email
docwb.api.email.draft.url=${docwb.base.url}/api/v1/email/draft
docwb.api.recommendation.url=${docwb.base.url}/api/v1/action/recommendation
docwb.api.attr.name.url=${docwb.base.url}/api/v1/attribute/names
docwb.api.attr.export.url=${docwb.base.url}/api/v1/attribute/export
docwb.api.ann.add.url=${docwb.base.url}/api/v1/annotation/add