# =============================================================================================================== #
# Copyright 2020 Infosys Ltd.                                                                                    #
# Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at    #
# http://www.apache.org/licenses/ 
# ================================================================================================================ #



startExecution=INSERT INTO EXECUTION (EXECUTOR_TYPE_CDE, EXECUTION_TITLE, TENANT_ID, CLIENT, START_DTM, CREATE_BY) \
			   VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP, ?) RETURNING EXECUTION_ID
endExecution=UPDATE EXECUTION SET END_DTM = CURRENT_TIMESTAMP, LAST_MOD_BY = ?, \
		     RUN_DURATION_SECS = EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - START_DTM)) \
		     WHERE EXECUTION_ID=?
addEvent=INSERT INTO EXECUTION_EVENT_REL(EXECUTION_ID, EVENT_TYPE_CDE, EVENT_DTM, \
		 EVENT_MSG, CREATE_BY) VALUES (?,?,CURRENT_TIMESTAMP,?,?) RETURNING EXEC_EVENT_REL_ID
updateEventMsg=UPDATE EXECUTION_EVENT_REL SET EVENT_MSG = ?, LAST_MOD_BY=? WHERE EXEC_EVENT_REL_ID = ? 		 
addTransaction=INSERT INTO TRANSACTION(TRANSACTION_EXT_ID, KEY_NAME, KEY_VALUE, STATUS_TYPE_CDE,CREATE_BY,TRANSACTION_EXT_START_DTM) \
			VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP) RETURNING TRANSACTION_ID
updateExtTransactionStatus=UPDATE TRANSACTION SET TRANSACTION_EXT_STATUS_TXT=?, LAST_MOD_BY = ?, \
		     TRANSACTION_EXT_END_DTM = CURRENT_TIMESTAMP \
		     WHERE TRANSACTION_EXT_ID=? AND TRANSACTION_EXT_END_DTM IS NULL AND END_DTM IS NULL
updateTransactionStatus=UPDATE TRANSACTION SET STATUS_TYPE_CDE = ?, TRANSACTION_EXT_MESSAGE=?, LAST_MOD_BY = ?, \
		     END_DTM = CURRENT_TIMESTAMP \
		     WHERE TRANSACTION_EXT_ID=? AND END_DTM IS NULL
getKeyPair=SELECT KEY_NAME,KEY_VALUE FROM TRANSACTION WHERE TRANSACTION_EXT_ID=?
getTransactionByStatus=SELECT * FROM TRANSACTION WHERE STATUS_TYPE_CDE=? AND END_DTM IS NULL
getValue=SELECT VALUE FROM KEY_VAL_MAP WHERE KEY =?
updateKeyValue=UPDATE KEY_VAL_MAP SET VALUE = ?, LAST_MOD_BY = ? WHERE KEY =?
addKeyValue=INSERT INTO KEY_VAL_MAP (KEY,VALUE,CREATE_BY) VALUES (?,?,?) RETURNING KEY_VAL_MAP_ID