# ===============================================================================================================#
# Copyright 2022 Infosys Ltd.                                                                                    #
# Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at  #
# http://www.apache.org/licenses/                                                                                #
# ===============================================================================================================#

[DEFAULT]
ENVIRONMENT = demo
APP_DIR_ROOT_PATH = c:/workarea/docwbdx
APP_DIR_DATA_PATH=%(APP_DIR_ROOT_PATH)s/data
APP_DIR_LOG_PATH=%(APP_DIR_ROOT_PATH)s/logs

# Path to log file
log_file_path = %(APP_DIR_LOG_PATH)s
log_file_prefix = infy_dx_indexer_
log_to_console = true
logging_level = 10
# Possible Values for logging_level
; CRITICAL = 50
; ERROR = 40
; WARNING = 30
; INFO = 20
; DEBUG = 10


service_name = infy_dx_indexer
# make sure the version is same as the one kept in setup.py
service_version = 0.0.1
output_file_suffix = infy_dx_indexer

[CONTAINER]
### Container related properties ###
CONTAINER_ROOT_PATH = /data/CONTAINER

