# =============================================================================================================== #
# Copyright 2024 Infosys Ltd.                                                                                    #
# Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at    #
# http://www.apache.org/licenses/ 
# ================================================================================================================ #

sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.password=sonar@123
sonar.projectKey=docwb-core
sonar.projectName=docwb-core
sonar.token=sqp_cbb6498d6120de2518d4c0c55dce03908b6a1edb
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/target/**
sonar.java.binaries=.
sonar.sources=.
sonar.typescript.lcov.reportPaths=coverage/lcov.info