# ===============================================================================================================#
# Copyright 2022 Infosys Ltd.                                                                                    #
# Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at  #
# http://www.apache.org/licenses/                                                                                #
# ===============================================================================================================#

[DEFAULT]
ENVIRONMENT = demo
APP_DIR_ROOT_PATH = c:/workarea/docwbdx
APP_DIR_DATA_PATH=%(APP_DIR_ROOT_PATH)s/data
APP_DIR_LOG_PATH=%(APP_DIR_ROOT_PATH)s/logs
# Path to log file
log_file_path = %(APP_DIR_LOG_PATH)s
log_file_prefix = infy_dx_preprocessor_
log_to_console = true
logging_level = 10
# Possible Values for logging_level
; CRITICAL = 50
; ERROR = 40
; WARNING = 30
; INFO = 20
; DEBUG = 10
max_workers = 4
max_size_limit_mb_azure_read = 50
max_size_limit_mb_azure_ocr = 50
max_size_limit_mb_tesseract = 200
max_size_limit_mb_abbyy = 200

min_max_dimension_azure_read=50*50,10000*10000
min_max_dimension_azure_ocr=50*50,10000*10000
min_max_dimension_tesseract=1*1,32767*32767
min_max_dimension_abbyy=1*1,32512*32512 

service_name = infy_dx_preprocessor
# make sure the version is same as the one kept in setup.py
service_version = 0.0.11
output_file_suffix = pre_processor_response



#tool flag "pdfbox" - to use java tool, "xpdf" - to use xpf executable win tool 
tool_flag=pdfbox

docwb_ocr_supported_file_types=*.png,*.jpeg,*.jpg,*.jpe,*.jfif,*.pdf
# application will fail when restricted file type found.
docwb_restricted_file_types=*.exe

process_file_batch_enabled=true
process_file_batch_count=10

azure_read_api_delay_sec=6
azure_read_submit_req_log_path=%(APP_DIR_LOG_PATH)s/azure_submit_req_result

max_retry_limit_post_ocr_failure=2

[WORKFLOW]
prev_stage_prefix=_downloader
current_stage_prefix=_prepro
prev_scheduler_stage_folder=app_scheduler_stage/downloader_completed
current_scheduler_stage_folder=app_scheduler_stage/prepro_completed
current_scheduler_stage_folder_error=app_scheduler_stage/error

[APP_ARGS]
# use / for file paths
master_config = C:/nfs/docwbdx/config/master_client_config.json


[TEMPLATE]
# preprocess_config_file_paths can contain "," separated multiple files
preprocess_config_file_paths = ../config/document_preprocess_config.json

[TELEMETRY]
LOG_EVENT_SUCCESS_ID=APP_DX_PROCESSOR-EXECUTE_DOCUMENT_SUCCESS
LOG_EVENT_FAILURE_ID=APP_DX_PROCESSOR-EXECUTE_DOCUMENT_FAILED