# ===============================================================================================================#
# Copyright 2022 Infosys Ltd.                                                                                    #
# Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at  #
# http://www.apache.org/licenses/                                                                                #
# ===============================================================================================================#

[DEFAULT]
ENVIRONMENT = dev
APP_DIR_ROOT_PATH = /home/projadmin/workarea/docwbsln
APP_DIR_DATA_PATH=/nfs/docwbdx/data
APP_DIR_LOG_PATH=/nfs/docwbdx/logs
# Path to log file
log_file_path = %(APP_DIR_LOG_PATH)s
log_file_prefix = infy_dx_casecreator_
logging_level = 10
; ERROR = 40
; WARNING = 30
; INFO = 20
; DEBUG = 10
log_to_console = true
service_name = infy_dx_casecreator
# make sure the version is same as the one kept in setup.py
service_version = 0.0.9
output_file_suffix = case_creator_response

[THREAD]
thread_pool_max_worker_count=4

[APP_ARGS]
# use / for file paths
; master_config = %(APP_DIR_DATA_PATH)s/config/master_client_config.json
; For local, directly refer to nearby config folder outside project folder
master_config = /nfs/docwbdx/config/master_client_config.json

[WORKFLOW]
prev_scheduler_stage_folder=app_scheduler_stage/postpro_completed
current_scheduler_stage_folder=app_scheduler_stage/casecreate_completed
current_scheduler_stage_folder_error=app_scheduler_stage/error


[TELEMETRY]
LOG_EVENT_SUCCESS_ID=APP_DX_PROCESSOR-EXECUTE_DOCUMENT_SUCCESS
LOG_EVENT_FAILURE_ID=APP_DX_PROCESSOR-EXECUTE_DOCUMENT_FAILED