# =============================================================================================================== #
# Copyright 2020 Infosys Ltd.                                                                                    #
# Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at    #
# http://www.apache.org/licenses/ 
# ================================================================================================================ #



audit.action.insert.message=Action executed
audit.action.update.message=Action updated : [{ENTITY_IDENTIFIER}]
audit.action.delete.message=Action deleted
audit.attachment.insert.message=Attachment added
audit.attachment.relation.insert.message=Attachment related
audit.attribute.insert.message=Attribute added [(ENTITY)]
audit.attribute.update.message=Attribute updated [(ENTITY)] : [{ENTITY_IDENTIFIER}]
audit.attribute.delete.message=Attribute deleted [(ENTITY)]
audit.multi.attribute.table.insert.message=Table Data added [(ENTITY)] : [{ENTITY_IDENTIFIER}]
audit.multi.attribute.table.update.message=Table Data updated [(ENTITY)] : [{ENTITY_IDENTIFIER}]
audit.multi.attribute.table.delete.message=Table Data deleted [(ENTITY)] : [{ENTITY_IDENTIFIER}]
audit.case.insert.message=Case created
audit.case.update.message=Case status updated
audit.case.delete.message=Case deleted
audit.email.send.insert.message=Outbound email saved
audit.email.send.message = Email status updated : [{ENTITY_IDENTIFIER}]
audit.email.insert.message=Draft email saved
audit.email.update.message=Draft email updated : [{ENTITY_IDENTIFIER}]
audit.email.delete.message=Email deleted
audit.case.assignment.update.message=Case {ROLE_TYPE_TXT} reassigned
audit.case.assignment.insert.message=Case {ROLE_TYPE_TXT} assigned
audit.role.insert.message=Role assigned
audit.role.update.message=Role updated
audit.role.delete.message=Role deleted
audit.user.insert.message=New user registered
audit.user.enable.status.update.message=Account status updated
audit.user.password.update.message=Password updated
audit.queue.assignment.delete.message=Removed user from queue
audit.queue.assignment.insert.message=Added user to queue
audit.queue.insert.message=Queue created
