# =============================================================================================================== #
# Copyright 2020 Infosys Ltd.                                                                                    #
# Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at    #
# http://www.apache.org/licenses/ 
# ================================================================================================================ #


addAudit=INSERT INTO APP_AUDIT (ENTITY_NAME,ENTITY_VALUE,AUDIT_MESSAGE,CURRENT_VALUE,PREVIOUS_VALUE,AUDIT_LOGIN_ID,CREATE_BY,TENANT_ID,AUDIT_EVENT_DTM) \
			  VALUES(?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) RETURNING app_audit_id
addDocAudit=INSERT INTO DOC_AUDIT_REL (APP_AUDIT_ID,DOC_ID,CREATE_BY,TENANT_ID) \
			  VALUES(?,?,?,?) RETURNING doc_audit_rel_id
addUserAudit=INSERT INTO USER_AUDIT_REL (APP_AUDIT_ID,APP_USER_ID,CREATE_BY,TENANT_ID) \
			  VALUES(?,?,?,?) RETURNING user_audit_rel_id
actionValue=SELECT DAR.DOC_ID,ACT.ACTION_NAME_TXT,TSV.TASK_STATUS_TXT,DAR.ACTION_RESULT, DAR.SNAP_SHOT FROM DOC_ACTION_REL DAR JOIN ACTION_NAME ACT ON \
	DAR.ACTION_NAME_CDE=ACT.ACTION_NAME_CDE AND DAR.TENANT_ID=ACT.TENANT_ID JOIN TASK_STATUS_VAL TSV ON \
	DAR.TASK_STATUS_CDE=TSV.TASK_STATUS_CDE WHERE {COLUMN_NAME}=? AND DAR.TENANT_ID=?
docattributeValue=SELECT DATR.DOC_ID,ATR.ATTR_NAME_TXT,ATTR.ATTR_VALUE FROM DOC_ATTR_REL DATR,ATTRIBUTE_NAME ATR, ATTRIBUTE ATTR \
	WHERE DATR.ATTRIBUTE_ID=ATTR.ATTRIBUTE_ID AND ATTR.ATTR_NAME_CDE=ATR.ATTR_NAME_CDE AND DATR.TENANT_ID=ATR.TENANT_ID AND DATR.TENANT_ID=ATTR.TENANT_ID AND {COLUMN_NAME}=? AND DATR.TENANT_ID=?
attachattributeValue=SELECT DAR.DOC_ID,ATR.ATTR_NAME_TXT,ATTR.ATTR_VALUE FROM ATTACHMENT_ATTR_REL AATR,ATTRIBUTE_NAME ATR, \
	ATTRIBUTE ATTR, DOC_ATTACHMENT_REL DAR WHERE {COLUMN_NAME}=? AND AATR.ATTRIBUTE_ID=ATTR.ATTRIBUTE_ID AND \
	ATTR.ATTR_NAME_CDE=ATR.ATTR_NAME_CDE AND AATR.TENANT_ID=ATR.TENANT_ID AND AATR.TENANT_ID=ATTR.TENANT_ID \
	AND AATR.ATTACHMENT_ID=DAR.ATTACHMENT_ID AND AATR.TENANT_ID=DAR.TENANT_ID AND AATR.TENANT_ID=?
attachmentValue=SELECT DATTR.DOC_ID,ATT.LOGICAL_NAME FROM DOC_ATTACHMENT_REL DATTR JOIN ATTACHMENT ATT ON DATTR.ATTACHMENT_ID=ATT.ATTACHMENT_ID \
	AND DATTR.TENANT_ID=ATT.TENANT_ID WHERE {COLUMN_NAME}=? AND DATTR.TENANT_ID=?
getattachmentValue=SELECT ATT.LOGICAL_NAME FROM  ATTACHMENT ATT WHERE {COLUMN_NAME} = ? AND ATT.TENANT_ID = ?
docValue=SELECT DOC.DOC_ID,TSV.TASK_STATUS_TXT FROM DOCUMENT DOC JOIN TASK_STATUS_VAL TSV ON DOC.TASK_STATUS_CDE=TSV.TASK_STATUS_CDE WHERE {COLUMN_NAME}=? AND DOC.TENANT_ID=?
emailValue=SELECT EO.DOC_ID,EO.TASK_STATUS_CDE,TSV.TASK_STATUS_TXT,EO.EMAIL_SUBJECT FROM EMAIL_OUTBOUND EO JOIN TASK_STATUS_VAL TSV ON EO.TASK_STATUS_CDE=TSV.TASK_STATUS_CDE WHERE {COLUMN_NAME}=? AND EO.TENANT_ID=?
assignmentValue=SELECT DAPU.DOC_ID,AU.USER_FULL_NAME FROM DOC_APP_USER_REL DAPU JOIN APP_USER AU ON DAPU.APP_USER_ID=AU.APP_USER_ID \
	AND DAPU.TENANT_ID=AU.TENANT_ID WHERE {COLUMN_NAME}=? AND DAPU.TENANT_ID=?
roleValue=SELECT APUR.APP_USER_ID,RTV.ROLE_TYPE_TXT FROM APP_USER_ROLE_REL APUR JOIN ROLE_TYPE_VAL RTV ON APUR.ROLE_TYPE_CDE=RTV.ROLE_TYPE_CDE WHERE {COLUMN_NAME}=? AND APUR.TENANT_ID=?
queueValue=SELECT APUQ.APP_USER_ID,QNV.QUEUE_NAME_TXT FROM APP_USER_QUEUE_REL APUQ JOIN QUEUE_NAME QNV ON APUQ.QUEUE_NAME_CDE=QNV.QUEUE_NAME_CDE AND APUQ.TENANT_ID=QNV.TENANT_ID WHERE {COLUMN_NAME}=? AND APUQ.TENANT_ID=?
userValue=SELECT APP.APP_USER_ID,APP.USER_FULL_NAME,APP.ACCOUNT_ENABLED FROM APP_USER APP \
		WHERE {COLUMN_NAME}=? AND APP.TENANT_ID=?
getAuditForDoc=SELECT AUDIT_LOGIN_ID,AUDIT_MESSAGE,CURRENT_VALUE,PREVIOUS_VALUE,AUDIT_EVENT_DTM,AU.USER_TYPE_CDE FROM APP_AUDIT A JOIN DOC_AUDIT_REL DAR \
	ON A.APP_AUDIT_ID = DAR.APP_AUDIT_ID AND A.TENANT_ID=DAR.TENANT_ID LEFT JOIN APP_USER AU ON \
	A.AUDIT_LOGIN_ID=AU.USER_LOGIN_ID AND A.TENANT_ID=AU.TENANT_ID WHERE DAR.DOC_ID= ? AND DAR.TENANT_ID=? \
	ORDER BY AUDIT_EVENT_DTM DESC
getAuditForUser=SELECT AUDIT_LOGIN_ID,AUDIT_MESSAGE,CURRENT_VALUE,PREVIOUS_VALUE,AUDIT_EVENT_DTM FROM APP_AUDIT A JOIN USER_AUDIT_REL UAR \
	ON A.APP_AUDIT_ID = UAR.APP_AUDIT_ID AND A.TENANT_ID=UAR.TENANT_ID WHERE UAR.APP_USER_ID = ? \
	AND UAR.TENANT_ID= ? ORDER BY AUDIT_EVENT_DTM DESC
getAuditForAppVariable=SELECT AUDIT_LOGIN_ID,AUDIT_MESSAGE,CURRENT_VALUE,PREVIOUS_VALUE,AUDIT_EVENT_DTM FROM APP_AUDIT \
	WHERE ENTITY_NAME = ? AND ENTITY_VALUE=? AND TENANT_ID= ? ORDER BY AUDIT_EVENT_DTM DESC
getDocAuditCount=SELECT COUNT(*) FROM APP_AUDIT A JOIN DOC_AUDIT_REL DAR ON A.APP_AUDIT_ID = DAR.APP_AUDIT_ID AND A.TENANT_ID=DAR.TENANT_ID WHERE DAR.DOC_ID= ? AND DAR.TENANT_ID=?
getUserAuditCount=SELECT COUNT(*) FROM APP_AUDIT A JOIN USER_AUDIT_REL UAR ON A.APP_AUDIT_ID = UAR.APP_AUDIT_ID AND A.TENANT_ID=UAR.TENANT_ID WHERE UAR.APP_USER_ID= ? AND UAR.TENANT_ID=?
getAuditForAppVariableCount=SELECT COUNT(*) FROM APP_AUDIT WHERE ENTITY_NAME = ? AND ENTITY_VALUE=? AND TENANT_ID= ?
getAuditForCurrentUserAtDocLevel=SELECT * FROM ( \
		SELECT AUD.APP_AUDIT_ID, \
			DAR.DOC_ID, \
			DOC.QUEUE_NAME_CDE, \
			AUD.AUDIT_LOGIN_ID, \
			AUD.AUDIT_MESSAGE, \
			AUD.CURRENT_VALUE, \
			AUD.PREVIOUS_VALUE, \
			AUD.AUDIT_EVENT_DTM, \
			MAX(AUD.APP_AUDIT_ID) OVER (PARTITION BY DAR.DOC_ID) \
		FROM APP_AUDIT AUD, DOC_AUDIT_REL DAR, DOCUMENT DOC \
		WHERE AUD.APP_AUDIT_ID = DAR.APP_AUDIT_ID \
			AND DOC.DOC_ID = DAR.DOC_ID \
			AND AUD.TENANT_ID = DAR.TENANT_ID \
			AND DOC.TENANT_ID = DAR.TENANT_ID \
			AND DOC.TENANT_ID = ? \
			AND LOWER(AUD.AUDIT_LOGIN_ID) = LOWER(?) \
		ORDER BY AUD.app_audit_id DESC \
		LIMIT ? ) X \
	WHERE X.MAX = X.APP_AUDIT_ID \
	ORDER BY APP_AUDIT_ID DESC