# =============================================================================================================== #
# Copyright 2020 Infosys Ltd.                                                                                    #
# Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at    #
# http://www.apache.org/licenses/ 
# ================================================================================================================ #



server.port=8099
server.servlet.context-path=/docwbrules
spring.application.name=Docwb Rules
server.shutdown=graceful

docwb.rules.logs.path=C:\\WorkArea\\DocumentWorkbench\\Logs

##### >>>>> SBA SECTION BEGIN
#To connect to SBA module as a client
spring.boot.admin.client.url=http://localhost:8100/docwbadmin
spring.boot.admin.client.username=admin
spring.boot.admin.client.password=admin

#Actuator Settings
management.port=8099
management.endpoints.web.exposure.include=*
management.endpoint.shutdown.enabled=true
##### <<<<< SBA SECTION END
