# =============================================================================================================== #
# Copyright 2020 Infosys Ltd.                                                                                    #
# Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at    #
# http://www.apache.org/licenses/ 
# ================================================================================================================ #



# Attribute Extractor
attribute-extractor.queue.name.cde=107,109,111,112,99

# Case Opener
case-opener.queue.name.cde=107,109,111,112,99

# Export Attributes
action.export-attributes.queue.name.cde=104,107,109,110,111,112,99
action.export-attributes.action.name.cde=202
action.export-attributes.path=C:/WorkArea/DocumentWorkbench/DATA/downstream/export

# Approve Passport
action.approve-passport.queue.name.cde=99
action.approve-passport.action.name.cde=200

# Reject Passport
action.reject-passport.queue.name.cde=99
action.reject-passport.action.name.cde=201

# Submit to SAP action properties
action.submit-to-sap.queue.name.cde=108,109,11,99
action.submit-to-sap.action.name.cde=203

# Get Acknowledgement Number
action.get-acknowledgement-number.queue.name.cde=-1
action.get-acknowledgement-number.action.name.cde=13

# workflow actions
action.data-entry-complete.queue.name.cde=-1
action.data-entry-complete.action.name.cde=204

action.data-entry-approve.queue.name.cde=-1
action.data-entry-approve.action.name.cde=206

action.data-entry-reject.queue.name.cde=-1
action.data-entry-reject.action.name.cde=205