# =============================================================================================================== #
# Copyright 2020 Infosys Ltd.                                                                                    #
# Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at    #
# http://www.apache.org/licenses/ 
# ================================================================================================================ #



app.logs.path=//home/projadmin/workarea/docwbsln/logs
app.logs.file.name.noextension=emailwb

docwb.service.base.url=http://localhost:80/docwbservice
docwb.service.api.auth.validate=${docwb.service.base.url}/api/v1/auth/validate

# NOTE:Unused properties so leave blank
elasticsearch.base.url=
elasticsearch.post.telemetry.api=
elasticsearch.username=
elasticsearch.drowssap=
