# ===============================================================================================================#
# Copyright 2020 Infosys Ltd.                                                                                    #
# Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at  #
# http://www.apache.org/licenses/                                                                                #
# ===============================================================================================================#


#URL
script.executor.base.url=http://localhost:8111/scriptexecutionmanager/WEMScriptExecService.svc
script.executor.api.initiate.execution.url=${script.executor.base.url}/InitiateExecution
script.executor.api.transaction.status.url=${script.executor.base.url}/GetTransactionStatus
