# =============================================================================================================== #
# Copyright 2020 Infosys Ltd.                                                                                    #
# Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at    #
# http://www.apache.org/licenses/ 
# ================================================================================================================ #



#Application Settings
server.port=8088
server.servlet.context-path=/docwbengine
spring.application.name=Docwb Engine 1
server.shutdown=graceful

#Concurrency Settings
core.thread.pool.count=20
max.thread.pool.count=20
scheduler.thread.pool.count=20

#Scheduler settings
document.downloader.interval.milliseconds=5000
document.downloader.cron=0 15 10 15 * ?
document.downloader.thread.pool.count=5
document.downloader.enabled=true

attribute.extractor.interval.milliseconds=5000
attribute.extractor.cron=0 15 10 15 * ?
attribute.extractor.thread.pool.count=5
attribute.extractor.enabled=true

case.opener.interval.milliseconds=30000
case.opener.interval.cron=0 15 10 15 * ?
case.opener.thread.pool.count=5
case.opener.enabled=false

action.executor.interval.milliseconds=30000
action.executor.cron=0 15 10 15 * ?
action.executor.thread.pool.count=5
action.executor.enabled=true

re.extract.action.executor.interval.milliseconds=30000
re.extract.action.executor.cron=0 15 10 15 * ?
re.extract.action.executor.enabled=false

action.script.executor.interval.milliseconds=30000
action.script.executor.cron=0 15 10 15 * ?
action.script.executor.enabled=false

action.script.result.updater.interval.milliseconds=15000
action.script.result.updater.cron=0 15 10 15 * ?
action.script.result.updater.enabled=false

email.sender.interval.milliseconds=30000
email.sender.cron=0 15 10 15 * ?
email.sender.enabled=false

#Database Settings
spring.datasource.url= jdbc:postgresql://hMDU1pyL:5423/docwbdb1?currentSchema=workflow&ApplicationName=DocwbEngine
spring.datasource.username=docwbengine
spring.datasource.password=docwbengine
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.type=org.apache.commons.dbcp2.BasicDataSource
spring.datasource.dbcp2.initial-size=5
spring.datasource.dbcp2.max-total=10
spring.datasource.dbcp2.max-idle=5
spring.datasource.dbcp2.min-idle=5
spring.datasource.dbcp2.default-query-timeout=300
spring.datasource.dbcp2.default-auto-commit=true

#URL
docwb.base.url=http://localhost:8080/docwbservice
docwb.username=docwbengine
docwb.drowssap=docwbengine
docwb.authenticate=true
docwb.thread.count=10
docwb.default.max.per.route=5

#tenant 
docwb.tenant.id =ae30c578-8569-4f86-be17-642ebaef2e52
docwb.engine.logs.path=C:/WorkArea/EmailWorkbench/Logs
docwb.engine.temp.path=C:/WorkArea/EmailWorkbench/DATA/temp

modelId=1
portfolioName=MYORG

service.email.classify.api.url=http://localhost:8201/emailclassifier/api/model/classify
#service.ner.predict.api.url=http://localhost:8202/nerpredictor/api/model/ner_predict
service.ner.predict.api.url=http://localhost:8202/nerpredictor/api/model/ner_predict
service.sentiment.api.url=http://localhost:8203/sentimentservice/api/model/sent_analysis

service.tabledataextractor.api.url=http://localhost:8200/tabledataextractor/api/v1/pdfdata
service.tabledataextractor.api.username=scott
service.tabledataextractor.api.drowssap=tiger

docwb.extractor.base.url=http://localhost:8098/docwbextractor
docwb.extractor.username=client
docwb.extractor.drowssap=client

service.attribute-extractor.socket-timeout-secs=180
service.ner-extractor.socket-timeout-secs=180

#Script Executor Service 
script.executor.base.url=http://localhost:8111/scriptexecutionmanager/WEMScriptExecService.svc

ds.email-server.basic.reader.client.connect=false
ds.file-system.reader.client.connect=true
ds.email-server.exchange.reader.client.connect=true

################### GENERAL WRITER ######################
dio.writer.basic.provider=com.infosys.ainauto.datainout.impl.basic.api.DataInOutProvider

################# EMAIL SERVER WRITER ###################
ds.email-server.writer.provider=com.infosys.ainauto.datasource.impl.emailserver.basic.api.EmailServerDataSourceProvider
#ds.email-server.writer.from.id=customersupport@testsmtp.com
ds.email-server.writer.from.id=customersupport@infosys.com
ds.email-server.writer.from.name=customersupport
#ds.email-server.writer.from.password=Infy123$
ds.email-server.writer.from.password=MailBox@1947
ds.email-server.writer.auth=false
#ds.email-server.writer.hostname=192.168.105.74
ds.email-server.writer.hostname=blrkecsmtp01
ds.email-server.writer.port=25
ds.email-server.writer.save.folder=Sent Items

################### GENERAL READER ######################
dio.reader.basic.provider=com.infosys.ainauto.datainout.impl.basic.api.DataInOutProvider
dio.reader.temp.path=C:/WorkArea/EmailWorkbench/DATA/temp

################# EMAIL SERVER BASIC READER ###################
ds.email-server.basic.reader.provider=com.infosys.ainauto.datasource.impl.emailserver.basic.api.EmailServerDataSourceProvider
ds.email-server.basic.reader.on-connection-error.ignore=true
ds.email-server.basic.reader.store.protocol=imap
ds.email-server.basic.reader.hostname=10.152.117.90
ds.email-server.basic.reader.port=143
ds.email-server.basic.reader.imap.ssl.enable=false
ds.email-server.basic.reader.default.folder=Inbox
ds.email-server.basic.reader.listen.folder=Inbox
ds.email-server.basic.reader.username=customersupport@chdsmtp.com
ds.email-server.basic.reader.password=Infy123+

################# FILE SYSTEM READER ###################
ds.file-system.reader.provider=com.infosys.ainauto.datasource.impl.filesystem.basic.api.FileSystemDataSourceProvider
ds.file-system.reader.on-connection-error.ignore=false
ds.file-system.reader.dir.source=C:/WorkArea/EmailWorkbench/DATA/upstream/input
ds.file-system.reader.dir.archival=C:/WorkArea/EmailWorkbench/DATA/upstream/archival

##Filter to INclude email satisfying criteria on subject field
#mail.subject.include.string.1=.*Sales.*
#mail.subject.include.string.2=.*Employee.*
#mail.subject.include.condition=OR
#
##Filter to EXclude email satisfying criteria on subject field
#mail.subject.exclude.string.1=.*data table.*
#mail.subject.exclude.condtion=OR

################# Email Server Exchange READER ###################
ds.email-server.exchange.reader.provider=com.infosys.ainauto.datasource.impl.emailserver.exchange.api.EmailServerDataSourceProvider
ds.email-server.exchange.reader.on-connection-error.ignore=true
ds.email-server.exchange.reader.domain=ITLINFOSYS
ds.email-server.exchange.reader.password=MailBox@1947
ds.email-server.exchange.reader.username=customersupport
ds.email-server.exchange.reader.service.uri=https://keccas.ad.infosys.com/ews/exchange.asmx
ds.email-server.exchange.reader.listen.folder=[LOCAL]

##### >>>>> SBA SECTION BEGIN
#To connect to SBA module as a client
spring.boot.admin.client.url=http://localhost:8100/docwbadmin
spring.boot.admin.client.username=admin
spring.boot.admin.client.password=admin

#Actuator Settings
management.port=8088
management.endpoints.web.exposure.include=shutdown,health,status,metrics,threaddump
management.endpoint.shutdown.enabled=true
##### <<<<< SBA SECTION END

file.word.extension.to.pdf=doc,docx
file.eml.extension.to.html=eml

email.sender.save.sent.mail.enabled=false