# =============================================================================================================== #
# Copyright 2020 Infosys Ltd.                                                                                    #
# Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at    #
# http://www.apache.org/licenses/ 
# ================================================================================================================ #



#Swagger Properties
springfox.documentation.swagger.v2.path=/swagger/json
#Thread Properties
core.thread.pool.count=25
max.thread.pool.count=30
#Database Properties

#Oracle jdbc Props
#jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#jdbc.url=jdbc:oracle:thin:@localhost:1521:xe?ApplicationName=DocwbService
#jdbc.username=docwbmain
#jdbc.password=docwbmain

#PostgreSQL jdbc Props
jdbc.driverClassName=org.postgresql.Driver
jdbc.url=jdbc:postgresql://localhost:5432/docwbdb?currentSchema=docwbmain&ApplicationName=DocwbService
jdbc.username=docwbweb
jdbc.drowssap=ZG9jd2J3ZWI=
jdbc.maxActive=50
jdbc.maxIdle=50
jdbc.minIdle=10

#Messaging Broker Props
messaging.broker.feature.enabled=true
messaging.broker.url=tcp://localhost:61616
messaging.broker.client.username=docwbservice
messaging.broker.client.drowssap=Infosys2020
messaging.broker.client.name=DocwbService

jwt.secret=freedom
jwt.expiry.secs=86400

# Note - For windows, format is C:\\Dir1\\Dir2. For Linux, format is //home/dir1/dir2
attachmentFilePath=//home/projadmin/workarea/docwbsln/data/docwbattachments
pageSize=25
pageSizeMax=100

docwb.service.logs.path=//home/projadmin/workarea/docwbsln/logs
docwb.service.temp.path=//home/projadmin/workarea/docwbsln/data/temp

docwb.service.rbac.enabled.rl.bit.position=2
docwb.service.rbac.map.config=rbac/rbacConfig.json
docwb.service.rbac.exclude.api.config=rbac/rbacExcludeApiConfig.json
docwb.service.feature.to.api.map.config=rbac/appFeatureToApiMappingConfig.json

mail.downloader.id=customercare@test.com

docwb.rules.base.url=http://localhost:8099/docwbrules
docwb.rules.api.template.list=${docwb.rules.base.url}/api/v1/template/list
docwb.rules.api.template.flattened=${docwb.rules.base.url}/api/v1/template/list/flattened
docwb.rules.api.attribute.notification=${docwb.rules.base.url}/api/v1/attribute/notification
docwb.rules.api.attribute.attribute.mapping=${docwb.rules.base.url}/api/v1/attribute/attribute/mapping
docwb.rules.api.attribute.sortkey=${docwb.rules.base.url}/api/v1/attribute/sortkey
docwb.rules.api.action.recommended=${docwb.rules.base.url}/api/v1/action/recommendation